version: "{build}"
configuration: Release
image: Visual Studio 2017

init:
  - ps: 'Update-AppveyorBuild -Version "1.0.$env:appveyor_build_number.$([math]::Truncate(((Get-Date) - (Get-Date -Year 2017 -Month 1 -Day 1 -Hour 0 -Minute 0 -Second 0)).TotalDays))"'

install:
  - ps: nuget restore src\AnalyzeThis.sln

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"

build:
  verbosity: minimal
  project: src\AnalyzeThis.sln
  publish_nuget: true

deploy:
  - provider: NuGet
    server: https://www.nuget.org
    api_key:
      secure: JKSF+JBSgoRDTd58vAFcg1vXm9sL2Cg2eBgU3w5088BZp9gIC0tqdjN8gwlxHNXS
    skip_symbols: true
    artifact: AnalyzeThis.$(appveyor_build_version).nupkg
    on:
      branch: master